version: '3'

services:
  app: 
    build: server
    depends_on:
      - db
    ports: 
      - '80:5000'
    volumes:
      - ./server:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pickflix
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
      - ./server/db:/data
    ports:
      - '5432:5432'